name: Generate .env File

on:
  workflow_call:
    inputs:
      api-url:
        required: true

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash -l {0}  
      run: |
        cat << EOF > .env
        VITE_API_URL=${{ inputs.api-url }}
        EOF
        cat .env