FROM node:20.12

ENV NODE_ENV development

WORKDIR /usr/app

RUN apt-get update \
&&  apt-get install -yq \
    git

RUN npm i -g pnpm

COPY package.json .
RUN pnpm install

COPY . .

EXPOSE 5173
CMD ["pnpm", "run", "dev"]